spring:
  datasource:
    password: ""
    url: jdbc:mysql://localhost:3306/kic_crm
    username: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
